name: CI/CD pipeline # active

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-push: # tên job
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and Push images
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # truyền vào biến trong docker-compose.yml
              run: | # sử dụng '|' để run được nhiều command, default chỉ có 1 command
                  docker compose -f docker-compose.yml build discoveryserver
                  docker compose -f docker-compose.yml push discoveryserver

    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.2.0
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SERVER_KEY }}
                  port: ${{ secrets.SERVER_PORT }}
                  envs: DOCKER_USERNAME
                  script_path: scripts/deploy.sh
